version: '3'

services:
  database:
    container_name: mysql_db
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: shoplivedb
      MYSQL_ROOT_PASSWORD: 1234
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - springmysql-net

  application:
    build: .
    image: backendtest
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mysql_db:3306/shoplivedb?useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    depends_on:
      - database
    networks:
      - springmysql-net

networks:
  springmysql-net: